config/routes.rb
Soundcloudradio::Application.routes.draw do
  resources :sessions
  resources :songs
  root :to => 'sessions#index'
  match '/callback', to: 'sessions#new', via: :get
  match '/login', to: 'sessions#create', via: :get
  match '/logout', to: 'sessions#destroy', via: :delete
  post '/songs/search_by_genre'

  

end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :artist, :title, :url
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :session_token, :username
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def set_current_user
    @current_user ||= session[:session_token] && User.find_by_session_token(session[:session_token])
    @local_redirect = 'http://localhost:3000/callback'
    @heroku_redirect = 'http://sradio.herokuapp.com/callback'
  end
end

app/controllers/sessions_controller.rb
require 'soundcloud'

class SessionsController < ApplicationController
  before_filter :set_current_user
  
  def new
    # create client object with app credentials
    client = Soundcloud.new(:client_id => 'f5f27bd7924819d49bd18ce5789e288a',
                            :client_secret => '51a9a1e4bd75af7b101e0fd6c988626e',
                            :redirect_uri => 'http://sradio.herokuapp.com/callback')
    
    # TODO: Add try to make sure that the access token is retrieved successfully
    error = params[:error]
    if error
      flash[:notice] = "Error: #{error}"
    else
      # exchange authorization code for access token
      code = params[:code]
      access_token = client.exchange_token(:code => code)
      
      # create client object with access token
      client = Soundcloud.new(:access_token => access_token[:access_token])
      
      # make an authenticated call
      current_user = client.get('/me')
      
      @user = User.find_by_username(current_user.username)
      
      params[:user] = {
        :username => current_user.username,
        :session_token => access_token[:access_token],
      }
      
      if @user
        @user.session_token = params[:user][:session_token]
        @user.save!
      else
        User.create!(params[:user])
      end

      session[:session_token] = params[:user][:session_token]
    end
    
    # TODO: Use a proper homepage
    redirect_to sessions_path
  end
  
  def create
    # create client object with app credentials
    client = Soundcloud.new(:client_id => 'f5f27bd7924819d49bd18ce5789e288a',
                            :client_secret => '51a9a1e4bd75af7b101e0fd6c988626e',
                            :redirect_uri => 'http://sradio.herokuapp.com/callback')
    
    # redirect user to authorize URL
    redirect_to client.authorize_url
  end
  
  def destroy
    session[:session_token] = nil
    redirect_to sessions_path
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_filter :set_current_user

  def search_by_genre
    if (params[:search_term] == nil) || (params[:search_term].blank? == true)
      flash[:notice] = "Invalid search term"
      redirect_to sessions_path
    else
      @searched_term = params[:search_term]
      client = SoundCloud.new(:client_id => 'd2e2927d267c9beb15ad51ad98e897c6')
      @songs_info = []
      tracks = client.get('/tracks', :limit => 30,:genres => @searched_term, :order => 'created_at', :offset => 30)
      tracks.each do |track|
        if track.stream_url
          songs_hash = {}
          songs_hash[:track] = track
          songs_hash[:title] = track.title
          songs_hash[:username] = track.user.username
          songs_hash[:url] = track.permalink_url
          songs_hash[:stream_url] = track.stream_url + '?client_id=d2e2927d267c9beb15ad51ad98e897c6'
          @songs_info.push(songs_hash)
        end
      end

      if tracks.count == 0
	      flash[:notice] = "No matching songs were found on Soundcloud"
        redirect_to sessions_path
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    # default: render 'new' template
    @user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title SoundCloud Radio
    = stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'
    = stylesheet_link_tag 'main'
    = javascript_include_tag 'audio'
    = javascript_include_tag 'jquery'
    = csrf_meta_tags

  %body
    .container
      %nav.navbar.navbar-inverse.navbar-fixed-top{:role => "navigation"}
        .container.container-fluid
          / Brand and toggle get grouped for better mobile display
          .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
              %span.sr-only Toggle navigation
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar

            %a.navbar-brand
              SoundCloud
              %span.glyphicon.glyphicon-headphones
              Radio
          / Collect the nav links, forms, and other content for toggling
          #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li.active
                %a{:href => "/sessions#index"} Home
            .form-group.navbar-form.navbar-left
              = form_tag songs_search_by_genre_path do
                = text_field_tag  :search_term, nil, class: "form-control"
                = submit_tag 'Search Sounds', class: "btn btn-default"
            %ul.nav.navbar-nav.navbar-right
              - if @songs_info
                %a.navbar-brand
                  %span.glyphicon.glyphicon-play#playPause
                %a.navbar-brand
                  %span.glyphicon.glyphicon-forward#skip
              - if @current_user
                %li
                  = button_to "Logout #{@current_user.username}", logout_path, :method => :delete, class: "btn btn-link"
              - else
                %li
                  = button_to 'Login', login_path, :method => :get, class: "btn btn-link"
          / /.navbar-collapse
        / /.container-fluid
      #main.row
        #content
          - if flash[:notice]
            %h2 #{flash[:notice]}
          - elsif flash[:warning]
            %h2 #{flash[:warning]}
          = yield

app/views/songs/search_by_genre.html.haml
%iframe{:width => "100%", :src => "https://w.soundcloud.com/player/?visual=true&url=https%3A%2F%2Fapi.soundcloud.com%2Ftracks%2F#{@songs_info[0][:id]}"}
:javascript
  $(function() {
          // Setup the player to autoplay the next track
          var a = audiojs.createAll({
            trackEnded: function() {
              var next = $('.list.playing').next();
              if (!next.length) next = $('.list').first();
              next.addClass('playing').siblings().removeClass('playing');
              audio.load($('.song', next).attr('data-src'));
              audio.play();
            }
          });

          // Load in the first track
          var audio = a[0];
          first = $('.song').attr('data-src');
          $('.list').first().addClass('playing');
          audio.load(first);

          $('#playPause').click(function(e) {
            audio.playPause();
            if (audio.playing) {
              document.getElementById("playPause").className = "glyphicon glyphicon-pause";
            }
            else {
              document.getElementById("playPause").className = "glyphicon glyphicon-play";
            }

          });

          //$('#skip').click(function(e) {
          //
          //});
        });
.jumbotron
  %h2 The following songs containing '#{@searched_term}' were found on SoundClound
  %br
  %table{:width => "100%"}
    %thead
      %tr
        %th Username
        %th Title
        %th URL
    %tbody
      %div
        %audio{:preload => ""}
        -#%tr
        -#  %td= @songs_info[0][:track]
        - @songs_info.each do |metainfo|
          %a.song{"data-src" => "#{metainfo[:stream_url]}", :href => "#", :style => "display:none"} &nbsp
          %tr
            %td= metainfo[:username]
            %td= metainfo[:title]
            %td= link_to "Link", metainfo[:url]